version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile.shortener
    ports:
      - '9000:9000'
    restart: always
    depends_on:
      - db
    volumes:
      - ./configs/conf.toml:/etc/shortlink/conf.toml
    networks:
      - backend

  db:
    build:
      context: .
      dockerfile: ./build/Dockerfile.db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=shortlink
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    driver: bridge
